# Generated by Django 3.2.4 on 2021-06-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_coin_p2p_transaction_usercoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='loss_or_gain',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
