# Generated by Django 3.2.4 on 2021-06-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_transaction_loss_or_gain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p2p',
            old_name='buy_amount',
            new_name='amount',
        ),
    ]
