# Generated by Django 3.2.4 on 2021-06-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_buy_amount_p2p_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2p',
            name='amount_in_inr',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
