# Generated by Django 3.2.4 on 2021-06-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_p2p_amount_in_inr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p2p',
            old_name='amount_in_inr',
            new_name='value_per_coin_inr',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='buy_amount_inr',
            new_name='value_per_coin_inr',
        ),
    ]
