# Generated by Django 3.2.4 on 2021-06-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210612_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2p',
            name='amount_in_inr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
