# Generated by Django 3.2.4 on 2021-07-10 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0010_alter_p2p_value_per_coin_inr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.FloatField()),
                ('price', models.FloatField()),
                ('price_per_coin_inr', models.FloatField()),
                ('total', models.FloatField()),
                ('fee', models.FloatField()),
                ('fee_in_inr', models.FloatField()),
                ('time', models.DateTimeField()),
                ('loss_or_gain', models.FloatField(blank=True, null=True)),
                ('buy_coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_coin', to='webapp.coin')),
                ('fee_coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_coin', to='webapp.coin')),
                ('sell_coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_coin', to='webapp.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
