# Generated by Django 3.2.4 on 2021-07-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210710_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='price_per_coin_inr',
            new_name='price_in_inr',
        ),
    ]
