# Generated by Django 3.2.4 on 2021-07-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_rename_price_per_coin_inr_trade_price_in_inr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buy_coin', to='webapp.coin'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='fee_coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_coin', to='webapp.coin'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sell_coin', to='webapp.coin'),
        ),
    ]
