# Generated by Django 3.2.4 on 2021-07-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20210711_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='buy_coin', to='webapp.coin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='fee_coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fee_coin', to='webapp.coin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_coin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sell_coin', to='webapp.coin'),
            preserve_default=False,
        ),
    ]
