# Generated by Django 3.2.4 on 2021-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210711_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='market',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
